name: CI
on:
  push:
    branches:
      - 'master'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build_debian_image:
    name: Build epicbox/debian image
    runs-on: [ self-hosted, small ]
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-debian
          image_name: debian
          image_tag: bullseye
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          add_hash: false
  build_clojure_image:
    name: Build epicbox-clojure image
    runs-on: [ self-hosted, small ]
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-clojure
          image_name: clojure
          image_tag: 1.9.0.397
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_gcc_image:
    name: Build epicbox-gcc image
    needs: build_debian_image
    runs-on: [ self-hosted, small ]
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-gcc
          image_name: gcc
          image_tag: 10.2.1
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_go_image:
    name: Build epicbox-go image
    runs-on: [ self-hosted, small ]
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-go
          image_name: go
          image_tag: 1.18.2.1
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_haskell_image:
    name: Build epicbox-haskell image
    runs-on: [ self-hosted, small ]
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-haskell
          image_name: haskell
          image_tag: 8.8.4
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_hyperskill_go_image:
    name: Build epicbox-hyperskill/go image
    runs-on: [ self-hosted, small ]
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-hyperskill/go
          image_name: hyperskill-go
          image_tag: 1.18.2
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_hyperskill_gcc_image:
    name: Build epicbox-hyperskill/gcc image
    needs: build_debian_image
    runs-on: [ self-hosted, small ]
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-hyperskill/gcc
          image_name: hyperskill-gcc
          image_tag: 10.2.1
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_hyperskill_gradle_image:
    name: Build epicbox-hyperskill/gradle image
    runs-on: [ self-hosted, small ]
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-hyperskill/gradle
          image_name: hyperskill-gradle
          image_tag: 8.5-jdk17
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_hyperskill_gradle_spring_image:
    name: Build epicbox-hyperskill/gradle-spring image
    runs-on: [ self-hosted, small ]
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-hyperskill/gradle-spring
          image_name: hyperskill-gradle-spring
          image_tag: 8.5-jdk17
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_hyperskill_java_image:
    name: Build epicbox-hyperskill/java image
    runs-on: [ self-hosted, small ]
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-hyperskill/java
          image_name: hyperskill-java
          image_tag: 17
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_hyperskill_node_image:
    name: Build epicbox-hyperskill/node image
    runs-on: [ self-hosted, small ]
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-hyperskill/node
          image_name: hyperskill-node
          image_tag: 18.17.1
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_hyperskill_node_javascript_image:
    name: Build epicbox-hyperskill/node-javascript image
    runs-on: [ self-hosted, small ]
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-hyperskill/node-javascript
          image_name: hyperskill-node-javascript
          image_tag: 18.17.1
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_hyperskill_python_image:
    name: Build epicbox-hyperskill/python image
    runs-on: [ self-hosted, small ]
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-hyperskill/python
          image_name: hyperskill-python
          image_tag: 3.10
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_java_image:
    name: Build epicbox/java image
    runs-on: [ self-hosted, small ]
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-java
          image_name: java
          image_tag: 23-slim
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_kotlin_image:
    name: Build epicbox/kotlin image
    runs-on: [ self-hosted, small ]
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-kotlin
          image_name: kotlin
          image_tag: 2.0.0
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_mono_image:
    name: Build epicbox/mono image
    needs: build_debian_image
    runs-on: [ self-hosted, small ]
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-mono
          image_name: mono
          image_tag: 6.10.0.104
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_node_image:
    name: Build epicbox/node image
    runs-on: [ self-hosted, small ]
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-node
          image_name: node
          image_tag: 18.17.1
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_php_image:
    name: Build epicbox/php image
    runs-on: [ self-hosted, small ]
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-php
          image_name: php
          image_tag: 7.2.6
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_pmd_image:
    name: Build epicbox/pmd image
    runs-on: [ self-hosted, small ]
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-pmd
          image_name: pmd
          image_tag: 6.9.0
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_python_310_image:
    name: Build epicbox/python 3.10 image
    runs-on: [ self-hosted, small ]
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-python/310
          image_name: python
          image_tag: 3.10.6
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_python_311_image:
    name: Build epicbox/python 3.11 image
    runs-on: [ self-hosted, small ]
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-python/311
          image_name: python
          image_tag: 3.11.5
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_ruby_image:
    name: Build epicbox/ruby image
    runs-on: [ self-hosted, small ]
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-ruby
          image_name: ruby
          image_tag: 2.5.3
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_scala2_image:
    name: Build epicbox/scala2 image
    runs-on: [ self-hosted, small ]
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-scala/2
          image_name: scala
          image_tag: 2.13.12
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_scala3_image:
    name: Build epicbox/scala3 image
    runs-on: [ self-hosted, small ]
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-scala/3
          image_name: scala
          image_tag: 3.0.0
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_typescript_image:
    name: Build epicbox/typescript image
    runs-on: [ self-hosted, small ]
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-typescript
          image_name: typescript
          image_tag: 4.8.4
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build_hyperstyle_image:
    name: Build epicbox/hyperstyle image
    runs-on: [ self-hosted, small ]
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          path: epicbox-hyperstyle
          image_name: hyperstyle
          image_tag: ij-2024.9
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

  clean_untagged_images:
    name: Clean untagged images
    needs:
      - build_clojure_image
      - build_debian_image
      - build_gcc_image
      - build_go_image
      - build_haskell_image
      - build_hyperskill_gcc_image
      - build_hyperskill_go_image
      - build_hyperskill_gradle_image
      - build_hyperskill_gradle_spring_image
      - build_hyperskill_java_image
      - build_hyperskill_node_image
      - build_hyperskill_node_javascript_image
      - build_hyperskill_python_image
      - build_java_image
      - build_kotlin_image
      - build_mono_image
      - build_node_image
      - build_php_image
      - build_pmd_image
      - build_python_310_image
      - build_python_311_image
      - build_ruby_image
      - build_scala2_image
      - build_scala3_image
      - build_typescript_image
      - build_hyperstyle_image
    runs-on: [ self-hosted, small ]
    timeout-minutes: 30
    steps:
      - uses: hyperskill/azure-purge-untagged@v3.0.0
        with:
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
          tenant_id: ${{ secrets.TENANT_ID }}
          repository_filter: epicbox/.*
          registry: hyperskill
